export const siteConfig = {
  title: "Время-деньги",
  description: "Generated by create next app",
	navItems: [
    {href: '/', label: 'Главная'},
    {href: '/orders', label: 'Заказы'},
    {href: '/about', label: 'О нас'},
  ],
}